### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: no implementation of "GraphQL.Client.Abstractions.Websocket.IGraphQLWebsocketJsonSerializer" found

### ISSUE THREAD

**Issue by AcellaEDU** [graphql-dotnet/graphql-client#178]
Construction **worked** - `var graphQLClient = new GraphQLHttpClient("http://xx.xxx.xxx.xxx/graphql");`

When I use construction type of
`serviceCollection.AddScoped<IGraphQLClient>(s => new GraphQLHttpClient("http://xx.xxx.xxx.xxx/graphql")`

I get **exception**:

`System.InvalidOperationException: no implementation of "GraphQL.Client.Abstractions.Websocket.IGraphQLWebsocketJsonSerializer" found
   at GraphQL.Client.Abstractions.GraphQLJsonSerializerExtensions.EnsureAssigned[TSerializerInterface](TSerializerInterface jsonSerializer)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(GraphQLHttpClientOptions options, HttpClient httpClient)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(GraphQLHttpClientOptions options)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(Action1 configure)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(Uri endPoint)
   at GraphQL.Client.Http.GraphQLHttpClient..ctor(String endPoint)`

**Solution**: 
`
serviceCollection.AddScoped<IGraphQLClient>(s => new GraphQLHttpClient(o =>
{
     o.EndPoint = new Uri("http://xx.xxx.xxx.xxx/graphql");
     o.JsonSerializer = new NewtonsoftJsonSerializer();
}))`

Related **issues**: #171

**Comment by AcellaEDU** [comment]
Is it a bug?

**Comment by rose-a** [comment]
Yes, it is, as stated in the second post in #171

**Comment by AcellaEDU** [comment]
@rose-a Thaks for your answer.
**Solution** from **DI**:

`return serviceCollection
.AddScoped<IGraphQLClient>(s => new GraphQLHttpClient("http://xx.xxx.xxx.xxx/graphql"))
.AddScoped<IGraphQLWebsocketJsonSerializer, NewtonsoftJsonSerializer>();`
