### ISSUE TITLE
Excepion while de-serializing the response - System.OverflowException: 'Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by madhusameena** [graphql-dotnet/graphql-client#193]
Exception details:
at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Int64.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at Newtonsoft.Json.Linq.Extensions.Value[U](IEnumerable`1 value)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadToken(JToken token)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadDictionary[TDictionary](JToken element)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadToken(JToken token)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadDictionary[TDictionary](JToken element)
   at GraphQL.Client.Serializer.Newtonsoft.GraphQLExtensionsConverter.ReadJson(JsonReader reader, Type objectType, GraphQLExtensionsType existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer.DeserializeFromUtf8Stream[T](Stream stream)
   at GraphQL.Client.Serializer.Newtonsoft.NewtonsoftJsonSerializer.DeserializeFromUtf8StreamAsync[TResponse](Stream stream, CancellationToken cancellationToken)
   at GraphQL.Client.Http.GraphQLHttpClient.<SendHttpPostRequestAsync>d__26`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at CloudService.Utils.GraphQL.GraphQLHelper.<CloudService-Utils-GraphQL-IGraphQLHelper-SendMutationAsync>d__0`2.MoveNext() in D:\Projects\ALSTER\IoT\DeviceDataService\Dev1\cloud-service-utils\src\CloudService.Utils\GraphQL\GraphQLHelper.cs:line 53
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.

I was trying to call a mutation
in my expected type - I don't have any int types
After debugging the code
I see that response as 
`{{
  "version": 1,
  "startTime": "2020-03-19T06:02:19.7791509Z",
  "endTime": "2020-03-19T06:02:39.7221509Z",
  "duration": 19942590700,
  "parsing": {
    "startOffset": 23599,
    "duration": 285900
  },
  "validation": {
    "startOffset": 326500,
    "duration": 1050100
  },
  "execution": {
    "resolvers": [
      {
        "path": [
          "dataready"
        ],
        "parentType": "Mutation",
        "fieldName": "dataready",
        "returnType": "DataReadyResponse",
        "startOffset": 1652300,
        "duration": 6282661100
      },
      {
        "path": [
          "dataready",
          "deviceType"
        ],
        "parentType": "DataReadyResponse",
        "fieldName": "deviceType",
        "returnType": "String!",
        "startOffset": 6284431899,
        "duration": 8264722700
      },
      {
        "path": [
          "dataready",
          "message"
        ],
        "parentType": "DataReadyResponse",
        "fieldName": "message",
        "returnType": "String!",
        "startOffset": 14549213799,
        "duration": 5372751600
      },
      {
        "path": [
          "dataready",
          "answer"
        ],
        "parentType": "DataReadyResponse",
        "fieldName": "answer",
        "returnType": "String!",
        "startOffset": 19922034900,
        "duration": 20483200
      }
    ]
  }
}}`

Getting error while converting `"duration": 19942590700,` to int
Don't know what this means - This is not part of graphql response

Please let me know - If I miss something

**Comment by sungam3r** [comment]
This is Apollo Trace extension info.

**Comment by sungam3r** [comment]
`GraphQLExtensionsConverter` should handle `long/ulong/etc.` numeric types as well as `int`.

**Comment by madhusameena** [comment]
@sungam3r 
Could you please guide me what should be done
Because in expected response class there is no int type
all properties are string types.
In response stream I was getting these additional info - No clue what can be done

**Comment by sungam3r** [comment]
Options:
1. Fix `GraphQLExtensionsConverter` to deserialize response properly, @rose-a may help.
2. Configure GraphQL server to not return Apollo Trace in GraphQL response.
3. Somehow cut Apollo Trace part from response **before** deserializing it (custom middleware, etc.).

**Comment by madhusameena** [comment]
@

> 
> 
> Options:
> 
>     1. Fix `GraphQLExtensionsConverter` to deserialize response properly, @rose-a may help.
> 
>     2. Configure GraphQL server to not return Apollo Trace in GraphQL response.
> 
>     3. Somehow cut Apollo Trace part from response **before** deserializing it (custom middleware, etc.).

Thank you for the response
If I want to remove Apollo Trace in server - Could you please guide me how to do that?

**Comment by sungam3r** [comment]
For .NET GraphQL Server project : https://github.com/graphql-dotnet/server/blob/develop/src/Core/GraphQLOptions.cs#L19

**Comment by madhusameena** [comment]
> 
> 
> For .NET GraphQL Server project : https://github.com/graphql-dotnet/server/blob/develop/src/Core/GraphQLOptions.cs#L19

Thank you for the suggestion
I will check this and get back to you

**Comment by madhusameena** [comment]
> 
> 
> For .NET GraphQL Server project : https://github.com/graphql-dotnet/server/blob/develop/src/Core/GraphQLOptions.cs#L19

I made `EnableMetrics` as false
After that that exception is gone 
But We see values are null in the de-serialized object - any clue what could be the problem?

We can see the values in other clients such as Insomnia

**Comment by sungam3r** [comment]
What values?

**Comment by madhusameena** [comment]
> 
> 
> What values?

After de-serialized to my class which contains 3 string properties - 
all property values are null

**Comment by sungam3r** [comment]
I can not give you a meaningful answer without seeing server response, your DTO and serializer settings.

**Comment by madhusameena** [comment]
Tried to read string from the stream(In `GraphQLHttpClient.SendHttpPostRequestAsync`) - We get 
`{"data":{"mutationName":{"testType":"Test","message":"Registered","answer":"Ok"}}}` as response
But our class to be de-serialized should have `{"testType":"Test","message":"Registered","answer":"Ok"}`
How can we ignore the remaining and get the only required data -i.e. class with 3 properties
`testType, message, answer` ?

**Comment by sungam3r** [comment]
I see you have parent object entry "mutationName". So I think you should deserialize into it:

`client.SendQueryAsync<A>(request)`

```c#
class A
{
  public B mutationName { get; set; }
}

class B
{
  public string testType {get;set;}
  public string message {get;set;}
  public string answer {get;set;}
}
```

**Comment by madhusameena** [comment]
Ohh I thought this will be handled automatically
And I will get only My response type.

But I can do what you are suggesting.
Thank you for that

**Comment by rose-a** [comment]
made a separate issue for fixing the converter (#194)

closing this.
