### ISSUE TITLE
Server error after deploying

### ISSUE THREAD

**Issue by barfootCBarragan** [graphql-dotnet/graphql-client#204]
I am able to use this library locally (I tested in different machines), however when I deploy to the server I am having the following error message:

GraphQL.Client -Version 2.1.2

> System.MissingMethodException: Method not found: 'System.Net.Http.HttpClient GraphQL.Client.Http.GraphQLHttpClient.get_HttpClient()'.
   at SalesKit.R2.Services.BarfootApiService.GetStaffFromGraphQl(String branchId, List`1 titleCodes)
   at SalesKit.R2.Business.BzApi.SearchAdmins(String searchText)
   at SalesKitR2.UI.Controllers.WebApi.BarfootApiController.SearchBranchAdmins(String search)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()

After trying latest version which was pushed 7 hours ago:

GraphQL.Client -Version 3.0.0

I have a building problem in the server: I have the same code as the repository sample

error CS1729: 'GraphQLHttpClient' does not contain a constructor that takes 1 arguments

**Comment by rose-a** [comment]
The error message is correct, as from V3.0.0 you have to explicitly pass a serializer to *GraphQLClient* via constructor parameter....
