### ISSUE TITLE
Error creating GraphQLHttpClient in Blazor preview3

### ISSUE THREAD

**Issue by julitogtu** [graphql-dotnet/graphql-client#206]
Hi all, I'm trying to create a new GraphQLHttpClient  in Blazor WebAssembly preview3 (latest preview), but an error in throw:

The code is simple:

`var graphQLClient = new GraphQLHttpClient("https://localhost:44367/graphql", new NewtonsoftJsonSerializer());`

I also tried with SystemTextJsonSerializer.

In the output window I get:

```
Stacktrace: 

Error
    at 643155 (https://localhost:44324/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:18963)
    at _emscripten_asm_const_iii (https://localhost:44324/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:19148)
    at wasm_logger (wasm-function[3118]:0x9c9ca)
    at eglib_log_adapter (wasm-function[6011]:0x10ed2f)
    at monoeg_g_logstr (wasm-function[4558]:0xcb37b)
    at monoeg_g_logv_nofree (wasm-function[2186]:0x62b0d)
    at monoeg_assertion_message (wasm-function[425]:0xd1b8)
    at mono_assertion_message_unreachable (wasm-function[141]:0x32a1)
    at create_thread (wasm-function[2979]:0x94c84)
    at ves_icall_System_Threading_Thread_Thread_internal (wasm-function[3260]:0xa0d80)
* Assertion: should not be reached at /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mono/utils/mono-threads-wasm.c:260

undefined
undefined
Uncaught RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.The thread 0x7324 has exited with code 0 (0x0).
The thread 0x4ddc has exited with code 0 (0x0).
The thread 0x4694 has exited with code 0 (0x0).
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.1.3\Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

I'm using GraphQL.Client v3.0.1.

I already tried some different ways to create the graphQLClient with the others constructors, but none works.

**Comment by rose-a** [comment]
Propably the same problam as #186... 

The exception only says that it reached an assertion which it shouldn't have reached.
I can't infer a tangible problem with *GraphQL.Client* from this!

Could you try to extract more info on what exactly is failing?

**Comment by rose-a** [comment]
Closing this in favor of #262
