### ISSUE TITLE
SystemTextJsonSerializer cannot (de)serialize Nullable<...> types

### ISSUE THREAD

**Issue by wirmar** [graphql-dotnet/graphql-client#234]
### Exception
```cs
System.InvalidCastException : Unable to cast object of type 'GraphQL.Client.Serializer.SystemTextJson.ImmutableConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[System.Nullable`1[System.Int32]]'.
   at System.Text.Json.JsonPropertyInfoCommon`4.set_ConverterBase(JsonConverter value)
   at System.Text.Json.JsonPropertyInfo.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type elementType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoCommon`4.Initialize(Type parentClassType, Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type elementType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonSerializer.GetRuntimeClassInfo(Object value, JsonClassInfo& jsonClassInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at GraphQL.Client.Serializer.SystemTextJson.SystemTextJsonSerializer.SerializeToString(GraphQLRequest request)
   at GraphQL.Client.Http.GraphQLHttpRequest.ToHttpRequestMessage(GraphQLHttpClientOptions options, IGraphQLJsonSerializer serializer)
   at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
   at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
...
```

### Reproducing the bug
```cs
        public class WithNullable
        {
            public int? NullableInt { get; set; }
        }

        [Test]
        public void ReproductionImmutableConverterBug()
        {
            var systemTextJsonSerializer = new SystemTextJsonSerializer();
            var serializedString = systemTextJsonSerializer.SerializeToString(new GraphQLRequest
            {
                Query = "{}",
                Variables = new WithNullable
                {
                    NullableInt = 2
                }
            });
        }
```

**Comment by rose-a** [comment]
Looks like *System.Text.Json* is not able to handle nullable integers properly...

**Comment by sungam3r** [comment]
I think the problem is in `ImmutableConverter` since it try to work for any type. If you look inside `JsonClassInfo.CreateProperty` you see `JsonPropertyInfoCommon`, `JsonPropertyInfoNotNullable` and `JsonPropertyInfoNullable`. Also maybe `Variables` should be `Dictionary<>`, not `WithNullable`.

**Comment by sungam3r** [comment]
The code that causes the error:
```c#
/// <summary>
    /// Represents a strongly-typed property to prevent boxing and to create a direct delegate to the getter\setter.
    /// </summary>
    internal abstract class JsonPropertyInfoCommon<TClass, TDeclaredProperty, TRuntimeProperty, TConverter> : JsonPropertyInfo
{
   public override JsonConverter ConverterBase
        {
            get
            {
                return Converter;
            }
            set
            {
                Debug.Assert(Converter == null);
                Debug.Assert(value is JsonConverter<TConverter>);  <----- Clear intent here

                Converter = (JsonConverter<TConverter>)value;
            }
        }
}
```

Maybe `ImmutableConverter.CanConvert` should return `false` on primitive types and their `Nullable<T>` types.

**Comment by rose-a** [comment]
> Maybe ImmutableConverter.CanConvert should return false on primitive types and their Nullable<T> types.

Sounds reasonable... The main purpose of `ImmutableConverter` is handling anonymous types...

**Comment by wirmar** [comment]
The error still occurs when serializing a Nullable struct (such as `Nullable<DateTime>`):
```cs
        public class WithNullableStruct
        {
            public DateTime? NullableStruct { get; set; }
        }

        [Fact]
        public void CanSerializeNullableStruct()
        {
            Action action = () => Serializer.SerializeToString(new GraphQLRequest
            {
                Query = "{}",
                Variables = new WithNullableStruct
                {
                    NullableStruct = DateTime.Now
                }
            });

            action.Should().NotThrow();
        }
```
