### ISSUE TITLE
Timeout issue?

### ISSUE THREAD

**Issue by jamiesin** [graphql-dotnet/graphql-client#314]
I am receiving the error below after 300 seconds, my request gets cancelled.

 

Anyone have ideas? Is there other request timeout settings in the library I need to be aware of?

 

My HttpClient is already: _client.Timeout = TimeSpan.FromMinutes(30);

 

2020/12/14 03:36:09        The HTTP request failed with status code 499

GraphQL.Client.Http.GraphQLHttpRequestException: The HTTP request failed with status code 499

   at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)

   at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)

**Comment by jamiesin** [comment]
Im on version 3.1.6.

**Comment by rose-a** [comment]
What's HTTP status code 499?
