### ISSUE TITLE
NullReferenceException after upgrade from 5.0.2 to 5.1.0

### ISSUE THREAD

**Issue by snifter** [graphql-dotnet/graphql-client#432]
If server response with status 401 and without Content-Type header a following exception is thrown.

```
System.NullReferenceException: Object reference not set to an instance of an object.

System.NullReferenceException
Object reference not set to an instance of an object.
   at GraphQL.Client.Http.GraphQLHttpClientOptions.<>c.<.ctor>b__44_2(HttpResponseMessage r) in /_/src/GraphQL.Client/GraphQLHttpClientOptions.cs:line 60
   at GraphQL.Client.Http.GraphQLHttpClient.SendHttpRequestAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken) in /_/src/GraphQL.Client/GraphQLHttpClient.cs:line 126
   at GraphQL.Client.Http.GraphQLHttpClient.SendQueryAsync[TResponse](GraphQLRequest request, CancellationToken cancellationToken)
```

In `GraphQL.Client.Http.GraphQLHttpClientOptions.IsValidResponseToDeserialize` should be changed to:
```
public Func<HttpResponseMessage, bool> IsValidResponseToDeserialize { get; set; } = r =>
        // Why not application/json? See https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#processing-the-response
        r.IsSuccessStatusCode || r.StatusCode == HttpStatusCode.BadRequest || r.Content.Headers.ContentType?.MediaType == "application/graphql+json";
```

**Comment by rose-a** [comment]
Hi, thanks for reporting, fix is incoming...
