### ISSUE TITLE
Json Serialiser doesn't handle structs well and ignores type converters

### ISSUE THREAD

**Issue by AlexeyRaga** [graphql-dotnet/graphql-client#622]
Hello,

I have some wrapper types that I want to use with GraphQL, which look like this:

```csharp
public struct ProductId(Guid value) {
    public Guid Value => value;

    public override string ToString() => value.ToString();
    public override bool Equals(object? obj) => obj is ProductId other && other.Value == value;
    public override int GetHashCode() => value.GetHashCode();
    public static bool operator ==(ProductId left, ProductId right) => left.Value == right.Value;
    public static bool operator !=(ProductId left, ProductId right) => !(left == right);
}
```

I also provide `JsonConverters` for these types, which look similar to:

```csharp
class FooSystemTextJsonConverter : JsonConverter<Foo>
{
    public override Foo Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        new Foo(Guid.Parse(reader.GetString()!));

    public override void Write(Utf8JsonWriter writer, Foo value, JsonSerializerOptions options) =>
        writer.WriteStringValue(value.Value);
}
```

I register the converters in the client:

```csharp
var serialiser = new SystemTextJsonSerializer
        {
            Options =
            {
                PropertyNameCaseInsensitive = true
            }
        };
serialiser.Options.Converter.Add(new ProductIdTypeConverter());
```

But when deserialising the GraphQL response I get this error:

```
System.InvalidOperationException
Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at GraphQL.Client.Serializer.SystemTextJson.ImmutableConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/GraphQL.Client.Serializer.SystemTextJson/ImmutableConverter.cs:line 80
```

I do not quite understand why `ImmutableConverter` was chosen and not the specific one that I registered...

I validated the approach, and it works if I create my wrapper types as `record`s somehow:

```csharp
public readonly record struct ProductId(Guid Value)
{
    public override string ToString() => Value.ToString();
}
```

But the goal is to make it work with plain structs and have libraries like https://github.com/lucasteles/Strongly to generate wrapper types, Json converters, and all the required boilerplate around them.

I believe that fixing the "plain structs" misbehavior would allow it to work rather smoothly.

**Comment by AlexeyRaga** [comment]
It probably boils down to the fact that this doesn't work:

```csharp
public readonly partial record struct ProductId
{
    public System.Guid Value { get; }

    public ProductId(System.Guid value)
    {
        Value = value;
    }
}
```

But this does work:

```csharp
public readonly partial record struct ProductId(Guid Value) {}
```

**Comment by AlexeyRaga** [comment]
Interestingly, it works if I use `Newtonsoft.Json` but not `System.Text.Json`

**Comment by rose-a** [comment]
Hi, sorry for the late reply...

> I do not quite understand why ImmutableConverter was chosen and not the specific one that I registered...

You could try to insert your custom converter at the beginning of the converters list (like [here](https://github.com/graphql-dotnet/graphql-client/blob/fbf37dfff2830e36a45296079bac27ec60fad550/src/GraphQL.Client.Serializer.SystemTextJson/SystemTextJsonSerializer.cs#L31)), this had to be done for the `ErrorPathConverter` and `MapConverter`, too.

**Comment by rose-a** [comment]
Yeah, I'd expect that to work, too.

But I don't know how to fine-tune the *System.Text.Json* serializer for that... PRs welcome :wink:

**Comment by AlexeyRaga** [comment]
@rose-a I may try to find some time to look into it... 
As a super quick and easy fix, would you accept this logic?

If the type is marked with `JsonConverterAttribute` (there is a converter for this type), `ImmutableConverter` should return `false` from `CanConvert` so that the registered converter can have its turn.

Also, could you please elaborate on the `ImmutableConverter`, why is it needed?

**Comment by rose-a** [comment]
> Also, could you please elaborate on the ImmutableConverter, why is it needed?

If I remember correctly it is needed for deserialization of anonymous types... If you're playing around, you could check what happens if you remove it (some tests should fail)

**Comment by AlexeyRaga** [comment]
> If you're playing around, you could check what happens if you remove it (some tests should fail)

Yeah, that's the thing.
I already checked it out, all the tests still pass if we remove `ImmutableConverter`.

I tried commenting out this line

https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client.Serializer.SystemTextJson/JsonSerializerOptionsExtensions.cs#L9

and even removing the whole `ImmutableConverter.cs` file, all the tests are happy.

Hence the question: why do we need it?

**Comment by rose-a** [comment]
Hm... trying to read up on this, it seems like this might have become obsolete wit .NET 5.0...

**Comment by AlexeyRaga** [comment]
If so, then it may fix the issue in a nicest way: fixing bugs by removing code :)

**Comment by rose-a** [comment]
@AlexeyRaga Could you please post a complete combination of class/struct and JsonConverter which shows the described behavior?
